name: ML Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull data from DVC
        run: |
          dvc pull data/processed/test.csv.dvc
          dvc pull models/model.cbm.dvc
        env:
          AWS_ACCESS_KEY_ID: dijwUT89Pd33o8DSRT4oFB
          AWS_SECRET_ACCESS_KEY: 46tY1bDm3TuX5UibGDbDUiuLN6orNdGnMqJBHCj5KSex

      - name: Predict model
        run: python src/models/model_predict.py -m models/model.cbm -d data/processed/test.csv -o data/processed/predictions.csv

      - name: Test model
        run: python src/tests/test_model.py -p data/processed/predictions.csv -t data/processed/test.csv